config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  get 'buy', to: 'users#buy'
  get 'all_users', to: 'users#all_users'
  get '/search', to: 'users#search'
  
  namespace :admin do
    resources :books do
      collection do
        get 'search'
      end
    end
    resources :plans
  end

  resources :issues, only: [:index, :new]
  resources :users 
  
end 

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  validates :name, presence: true
  validates :author, presence: true
  has_one :issue
  has_one_attached :image
  paginates_per 2
  acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
end

app/models/issue.rb
# frozen_string_literal: true

class Issue < ApplicationRecord
  belongs_to :user
end

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  validates :plan_name, presence: true
  validates :plan_description, presence: true, length: { in: 6..100 }
  has_many :users
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :book
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :plan, optional: true
  has_many :issues
  
end

app/controllers/admin/books_controller.rb
# frozen_string_literal: true

module Admin
  class BooksController < ApplicationController
    before_action :authenticate_user!

    def index
      @books = Book.order(:id).page params[:page]
    end

    def show
      @book = Book.find(params[:id])
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(book_params)
      if @book.save
        redirect_to admin_books_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @book = Book.find(params[:id])
    end

    def update
      @book = Book.find(params[:id])

      if @book.update(book_params)
        redirect_to admin_books_path
      else
        render :edit
      end
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to root_path
    end

    def search
      @books = Book.all.where('name LIKE :search OR author LIKE :search', search: "%#{params[:search]}%")
    end

    private

    def book_params
      params.require(:book).permit(:name, :author, :image, :tag_list)
    end
  end
end

app/controllers/admin/plans_controller.rb
# frozen_string_literal: true

module Admin
  class PlansController < ApplicationController
    before_action :authenticate_user!

    def index
      @plans = Plan.all
    end

    def show
      @plan = Plan.find(params[:id])
    end

    def new
      @plan = Plan.new
    end

    def create  
      @plan = Plan.new(plan_params)
      if @plan.save
        redirect_to admin_plans_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @plan = Plan.find(params[:id])
    end

    def update
      @plan = Plan.find(params[:id])
      if @plan.update(plan_params)
        redirect_to admin_plans_path
      else
        render :edit
      end
    end

    def destroy
      @plan = Plan.find(params[:id])
      @plan.destroy
      redirect_to admin_plans_path
    end

    private

    def plan_params
      params.require(:plan).permit(:plan_name, :plan_description, :plan_rate)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/issues_controller.rb
# frozen_string_literal: true

class IssuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.order(:id).page params[:page]
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(book_id: params[:book_id], user_id: params[:user_id])
    if @issue.save
      flash.now[:notice] = 'Issue book successfully'
      redirect_to issues_path, notice: 'Issue book succesfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :author)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.order(:id).page params[:page]
  end

  def buy
    @user = User.find_by_id params[:user][:id]
    if @user.update(plan_id: params[:user][:plan_id])
      UserMailer.with(user: @user).welcome_email.deliver_later
      redirect_to issues_path, notice: 'Mail send succesfully'
    else
      render :buy, status: :unprocessable_entity
    end
  end

  def all_users
    @users = User.where(plan_id: params[:plan_id])
  end

  def search
    @user = User.all.where('email LIKE :search ', search: "%#{params[:search]}%")
  end

  private

  def buy_params
    params.require(:user).permit(:plan_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/book_helper.rb
# frozen_string_literal: true

module BookHelper
end

app/helpers/issues_helper.rb
# frozen_string_literal: true

module IssuesHelper
end

app/helpers/plan_helper.rb
# frozen_string_literal: true

module PlanHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/books/_form.html.erb
<h1>form page</h1>
<%= form_with model: [:admin, @book]  do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_area :author %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :tag_list, "Tags (separated by commas)" %><br>
    <%= form.text_field :tag_list %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/books/_index.html.erb
<h1>Book</h1>

<%= paginate @books %>
<ul>
  <% @books.each do |book| %>
    <li>
        <% if book.image.attached? %>
          <image src="<%=(url_for(book.image))%>" style="height:20vw;width:15vw;">
          <%= rating_for book, 'book' %>
        <% end %><br>
        <%= link_to book.name, admin_book_path( id: book.id) %>
    </li>
  <% end %>
</ul>

app/views/admin/books/_search_book.html.erb
<%= form_with(url: '/admin/books/search', method: 'get') do |form| %>
		<%= text_field_tag(:search)%>
		<%= submit_tag("Search",name: nil)%>
<% end %>	

app/views/admin/books/edit.html.erb
<h1>Update Name & Author</h1>
<%= render "form", book: @book %>

app/views/admin/books/index.html.erb
<h1>Book</h1>
<%= link_to "New Book", new_admin_book_path %>
<%= render "admin/books/index", book: @book %> 

app/views/admin/books/new.html.erb
<h1>New Book</h1>
<%= render "form", book: @book %>

app/views/admin/books/search.html.erb
<h2>search book result </h2>
<% @books.each do |book| %>
	<%= book.name %><br/>
	<%= book.author %>
<% end %>	

app/views/admin/books/show.html.erb
<% if @book.image.attached? %>
    <image src="<%=(url_for(@book.image))%>", , style='height:20vw;width:15vw;'>
<% end %><br>
<h1><%= @book.name %></h1>
<p><%= @book.author %></p>

<ul>
  <% if current_user.admin? %>
    <li><%= link_to "Edit", edit_admin_book_path(id: @book.id) %></li>
    <li><%= link_to "Destroy", admin_book_path(id: @book.id), data: {
                      method: :delete,
                      confirm: "Are you sure?"
                    } %></li>
  <% else %>
    <% if(current_user.plan_id != nil) %>
      <%= link_to 'Issue Book',users_path(book_id: @book.id, user_id:current_user.id), method: :post %>
    <% else %>
      <%= link_to "Plans", admin_plans_path %></br>
    <% end %> 
                    
  <% end %> 

</ul>

app/views/admin/plans/_form.html.erb
<h1>form page</h1>
<%= form_with model: [:admin, @plan]  do |form| %>
  <div>
    <%= form.label :plan_name %><br>
    <%= form.text_field :plan_name %>
  </div>

  <div>
    <%= form.label :plan_description %><br>
    <%= form.text_area :plan_description %>
  </div>

  <div>
    <%= form.label :plan_rate %><br>
    <%= form.text_area :plan_rate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/plans/edit.html.erb
<h1>Edit Plan</h1>
<%= render "form", plan: @plan %>

app/views/admin/plans/index.html.erb
<h1>Our Plans</h1>
<%= link_to "Exit", users_path %>
<ul>
  <% @plans.each do |plan| %>
    <li>
      <%= link_to plan.plan_name,  admin_plan_path( id: plan.id) %>
    </li>
  <% end %>
</ul>

app/views/admin/plans/new.html.erb
<h1>New Plan</h1>
<%= render "form", plan: @plan %>

app/views/admin/plans/show.html.erb
<h1><%= @plan.plan_name %></h1>
<p><%= @plan.plan_description %></p>
<p><%= @plan.plan_rate %></p>

<ul>
  <% if current_user.admin? %>
    <li><%= link_to "Edit", edit_admin_plan_path(id: @plan.id) %></li>
    <li><%= link_to "Destroy", admin_plan_path(id: @plan.id), data: {
                  method: :delete,
                  confirm: "Are you sure?"
                } %></li><br/>
    <li><%= link_to "All Users", all_users_path(id: @plan.id) %> </li>     
  <% else %>
      <%= link_to "Buy now", buy_path(user: {id: current_user.id, plan_id: @plan.id}) %>
      
     
  <% end %>
</ul>

 

app/views/issues/index.html.erb
<h1>Issues#index</h1>
<p>Find me in app/views/issues/index.html.erb</p>
<%= render "admin/books/index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
  </body>

</html>

app/views/users/_search.html.erb
<%= form_with(url: '/search', method: 'get') do |form| %>
		<%= text_field_tag(:search)%>
		<%= submit_tag("Search",name: nil)%>
<% end %>	

app/views/users/all_users.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
    <li>
      <%= user.email %>
    </li>
<% end %><br/>

app/views/users/buy.html.erb
<h1>Buy View</h1>

app/views/users/index.html.erb
<br/>
<%= link_to "logout", destroy_user_session_path %>
<% if current_user.admin? %>
  <h1>Admin</h1>
  <%= link_to "Add Books", new_admin_book_path %>
  <%= link_to "Add Plan", new_admin_plan_path %> 
  <%= link_to "Our Plans", admin_plans_path %></br></br>
  <%= render "search" %>
<% else %>
  <ul>
    <h1>User</h1>
    <%= render "admin/books/search_book" %>
    <% if(current_user.plan_id != nil) %>
      <%= "Already have plan" %>
    <% else %>
      <%= link_to "Plans", admin_plans_path %></br>
    <% end %> 
  </ul>
<% end %>

<h3>All Books</h3>
 <%= paginate @books %>

 <% @books.each do |book| %>
   <% if book.image.attached? %>
     <image src="<%=(url_for(book.image))%>", style='height:20vw;width:15vw;'>
   <% end %>
  <ul>
    <li>
       <%= link_to book.name, admin_book_path( id: book.id) %>
    </li>
  </ul> 
 <% end %>

 

app/views/users/search.html.erb
<h2>search result </h2>
<% if @user.exists? %>
	<% @user.each do |user| %>
		<p> Email: </p>
		<%=  user.email %>

		<p> Plan: </p>
		<%=  user.plan.plan_name %>
	<% end %>
<% else %>
	<p> Sorry :) no user exists </p>
<% end %>	

app/views/users/show.html.erb
<%= form_tag(user_path, method: 'get') do %>
	<%= text_field_tag(:search, params[:search])%>
	<%= submit_tag("Search",name: nil)%>
<% end %>	 